### PR TITLE
Fix init for ZephyrOS

### PR DESCRIPTION
**Pull request by darshan1205**

### CODE REVIEW

**Comment by SarthakNarang** [comment]
This wont wrk. tried ages ago

**Comment by darshan1205** [comment]
Its working with tipsy ?

**Comment by SarthakNarang** [comment]
yus

**Comment by YumeMichi** [comment]
https://github.com/ashwinr64/android_device_oneplus_onyx/commit/d3ef9641700a43e8db86cedf58fa335b091a0e61

**Pull request closed without merging**
