### PR TITLE
Update your shit Sarthak!!!

### PR DESCRIPTION
**Pull request by EyeCantCU**
Jeeze... make the blind guy do it

### CODE REVIEW

**Comment by koradiavatsal** [comment]
+1, lacking updates as always. #BlameSarthak

**Comment by EyeCantCU** [comment]
lol #FuckNimit

**Comment by SaatvikShukla** [comment]
Seriously Sarthak, we trusted you with our devices and lives, and this is what we got? 
#BlameSarthak

**Comment by Martinusbe** [comment]
Oh lord 😱

**Comment by EyeCantCU** [comment]
I'm blind #BlameSarthak

**Comment by sud-vastav** [comment]
This was never expected of you, Sarthak! #BlameSarthak

**Pull request merged**
